### ISSUE TITLE
support windows

### ISSUE THREAD

**Issue by utkarshayachit** [diatomic/diy#52]
Windows builds fail as follows:
```
c:\...diy\storage.hpp(8): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

```

**Comment by mrzv** [comment]
The comment in `storage.hpp` says that it's using that file to get `mkstemp()` function on a Mac. So the easy part of the problem: we can just remove that include on Windows. The more complicated part of the problem is how to get some equivalent of `mkstemp()`. I don't use Windows (and I don't even have any Windows machines), so it's difficult for me to debug this.

**Comment by utkarshayachit** [comment]
working on it. I'll have an pr when ready.

**Comment by mrzv** [comment]
Did #59 close this? @utkarshayachit

**Comment by utkarshayachit** [comment]
yes..I am sure there'll be more iteration to fix warnings etc, but this can be closed.
