### ISSUE TITLE
Messages arrive out-of-order when using different instances of "master"

### ISSUE THREAD

**Issue by sujin-philip** [diatomic/diy#72]
I have attached a simple test that reproduces the issue. The issue is not hit all the time, so running the test multiple times may be needed. A simple workaround is to uncomment the barrier on line 95.

```c++
#include <diy/master.hpp>
#include <diy/mpi.hpp>

#include <cassert>
#include <iostream>
#include <vector>

template <typename T>
inline void PrintVector(std::ostream& out, const std::vector<T>& vec)
{
  out << "size = " << vec.size() << ", values = ";
  for (const T& val : vec)
  {
    out << val << " ";
  }
  out << "\n";
}

template <typename T>
void TestEqual(const std::vector<T>& v1, const std::vector<T>& v2)
{
  bool passed = (v1.size() == v2.size());
  if (passed)
  {
    for (std::size_t i = 0; i < v1.size(); ++i)
    {
      if(v1[i] != v2[i])
      {
        passed = false;
        break;
      }
    }
  }

  if (!passed)
  {
    std::cout << "v1: ";
    PrintVector(std::cout, v1);
    std::cout << "v2: ";
    PrintVector(std::cout, v2);
    abort();
  }
}

//-----------------------------------------------------------------------------
template <typename T>
struct Block
{
  T send;
  T received;
};

template <typename T>
void TestSerializationImpl(const T& obj)
{
  diy::mpi::communicator comm;
  Block<T> block;

  {
  diy::Master master(comm);

  auto nblocks = comm.size();
  diy::RoundRobinAssigner assigner(comm.size(), nblocks);

  std::vector<int> gids;
  assigner.local_gids(comm.rank(), gids);
  assert(gids.size() == 1);
  auto gid = gids[0];

  diy::Link* link = new diy::Link;
  diy::BlockID neighbor;

  // send neighbor
  neighbor.gid = (gid < (nblocks - 1)) ? (gid + 1) : 0;
  neighbor.proc = assigner.rank(neighbor.gid);
  link->add_neighbor(neighbor);

  // recv neighbor
  neighbor.gid = (gid > 0) ? (gid - 1) : (nblocks - 1);
  neighbor.proc = assigner.rank(neighbor.gid);
  link->add_neighbor(neighbor);

  block.send = obj;
  master.add(gid, &block, link);

  // compute, exchange, compute
  master.foreach([](Block<T> *b, const diy::Master::ProxyWithLink& cp) {
    cp.enqueue(cp.link()->target(0), b->send);
  });
  master.exchange();
  master.foreach([](Block<T> *b, const diy::Master::ProxyWithLink& cp) {
    cp.dequeue(cp.link()->target(1).gid, b->received);
  });

  //comm.barrier();
  }

  TestEqual(block.send, block.received);
}

//-----------------------------------------------------------------------------
int main(int argc, char *argv[])
{
  diy::mpi::environment mpienv(argc, argv);

  const std::size_t ArraySize = 10;

  for (int i = 0; i < 2; ++i)
  {
    std::vector<float> array(ArraySize);

    const float step = 0.73;
    float curval = 1.33 * static_cast<float>(i);
    for (auto& v : array)
    {
      v = curval;
      curval += step;
    }

    TestSerializationImpl(array);
  }

  std::cout << "Test completed successfuly\n";
  return 0;
}
```

[CMakeLists.txt](https://github.com/diatomic/diy/files/2210372/CMakeLists.txt)
[test.cxx.txt](https://github.com/diatomic/diy/files/2210395/test.cxx.txt)

**Comment by mrzv** [comment]
> Unsynchronized, here is what happens. Assume rank 0 finishes round 0 (enqueues, exchanges, dequeues) and moves to round 1 (enqueues, exchanges, dequeues). Meanwhile, its neighbor rank 1 lags and is still on round 0. The message that rank 1 had in its receive queue from rank 0, round 0 gets overwritten by the new message from rank 0, round 1. Now the send and receive messages at rank 1 don't match because the send message is from round 0 but the receive message is from round 1.

I don't get this. You are describing a single Master situation, which, as far as we know, works fine. The specific problem you are describing is solved by `exchange_round_` counter in Master.

> There are two possible fixes.
>
> * We put a barrier into the destructor of Master, the equivalent of the barrier in the example.
> * We change the buffer swap to an append, as we did in the iexchange mode. I assume the former is easier, and the latter will break something else, but we should discuss.

I'm perfectly happy with the first way, as long as we understand exactly what the problem is.

**Comment by tpeterka** [comment]
The single master situation works fine; I tested it. I was describing the multiple master situation. 

When Master is re-created, its exchange_round_ is reset. Because the masters' creation is unsynchronized, isn't it possible for the round 1 outgoing message of one master to overwrite the round 0 incoming message of another master?

**Comment by mrzv** [comment]
Let's call them Master1 and Master2. Rank 0 and 1, and round 0 and 1. You are saying that Master2, rank 1, round 0 incoming message could be overwritten by Master1, rank 0, round 1 outgoing message. What I don't understand is how Master 1, rank 1, round 1 could have ended without it receiving that message first?

**Comment by tpeterka** [comment]
![img_1909](https://user-images.githubusercontent.com/1747481/43165937-cc5aa604-8f5a-11e8-82b3-ea8b2bbb1d2f.JPG)

Let's try the above diagram. Time proceeds vertically downward. The data being enqueued is the same as the round number (value 0 is enqueued in round 0, value 1 in round 1). Rank 0 goes on to the round 1 with a new master while rank 1 is still in round 0. Rank 1 doesn't see data 0 because it is overwritten by data 1 before rank 1 has a chance to dequeue data 0. The overwrite is only possible because rank 0 created a new master with a reset exchange_round (I think).

**Comment by mrzv** [comment]
But doesn't this violate MPI's promise that messages with the same tag, on the same communicator are received in order? Messages that are sending `0` and `1` are sent on the same communicator, with the same tag.

**Comment by mrzv** [comment]
I wonder if it has to do with us using `iprobe` before `recv`. Although I don't see why it would.

**Comment by mrzv** [comment]
From MPI docs:

> **Order** Messages are *non-overtaking*: If a sender sends two messages in succession to the same destination, and both match the same receive, then this operation cannot receive the second message if the first one is still pending.

That's the part that confuses me.

**Comment by tpeterka** [comment]
No, I still think we are overwriting the message before it is exchanged. I should note also that sometimes the program hangs; it does not always crash with the mismatched messages. That's another indication that something else is going on, like unsynchronized masters. But for the mismatched messages case, here is a dump of my printfs for one of the crashes:

~/software/diy-bug/build $ mpiexec -n 3 ./mytest 
new master rank=0 round=0
new master rank=1 round=0
new master rank=2 round=0
enq'ing rank=1 round=0 send=0.00
enq'ing rank=0 round=0 send=0.00
enq'ing rank=2 round=0 send=0.00
deq'ing rank=0 round=0 received=0.00
checking rank=0 round=0 send=0.00 received=0.00
deq'ing rank=1 round=0 received=0.00
checking rank=1 round=0 send=0.00 received=0.00
new master rank=1 round=1
new master rank=0 round=1
enq'ing rank=0 round=1 send=1.33
enq'ing rank=1 round=1 send=1.33
deq'ing rank=2 round=0 received=1.33
checking rank=2 round=0 send=0.00 received=1.330

Note that I print only the first element of the data, which suffices. The first round data is 0.00 and the second round is 1.33. In this case, rank 2 was lagging (in my diagram of the previous post, it was rank 1). See how rank 2 never had a chance to dequeue 0.00 because rank 1 already changed masters and overwrote the message with 1.33. Rank 2 dequeues 1.33, but its send data is still 0.00, which triggers the error.

I can attach my code if it's not clear what I'm printing and where.

**Comment by mrzv** [comment]
Oh, I think I finally understand what's going on. It's not that anything gets overwritten per se, it's that the original message never goes out. The message rank 1 sends to 2 from the first master never goes out (the `isend` never goes through before the Master is destroyed, and there is no one left to nudge it). And then the `isend` from the second master is what actually gets matched with `recv`.  That would explain this behavior.

Then what happens under a barrier? MPI is implicitly testing all outstanding requests and makes sure that they are gone, before a barrier is executed? If so, then everything makes sense, and putting a barrier in the destructor is a good solution. Alternatively, we could make sure, in the destructor, that there are no outstanding outgoing messages in flight. Maybe that's better since it obviates a need for global synchronization?

We just need to check with one of the MPI experts that if there are outstanding asynchronous messages and a barrier is executed, MPI proceeds to "test" them. I think this makes sense: as long as MPI has control, presumably it would keep feeding time to any outstanding operations.

**Comment by tpeterka** [comment]
Ok, I think we're converging on the cause of the problem. As to the solution:

I don't think MPI does any tests while it's waiting in the barrier. I have not checked with Ken, but I'd be surprised if it did. Nevertheless, the result can be explained at the DIY level, without diving into MPI. The barrier prevents the master of the fast rank from destructing before the slow rank has caught up. That means both ranks executed the entire enqueue/exchange/dequeue protocol, meaning the message of the current round was sent and received before another round is begun.

The difference between the two ways of solving the problem (barrier or check for outstanding messages in the destructor), the latter would be more scalable because it would not cause a global synchronization. Assuming the check for outstanding outgoing messages is completely local, this would indeed be better.

**Comment by mrzv** [comment]
Actually, my theory was wrong. In `flush()`, one of the conditions is `while(!inflight_sends().empty())`, so I don't see how we can reach a Master destructor before all the messages actually go out at the MPI level. So I'm back to being confused.

> The barrier prevents the master of the fast rank from destructing before the slow rank has caught up. That means both ranks executed the entire enqueue/exchange/dequeue protocol, meaning the message of the current round was sent and received before another round is begun.

But if Master of the fast rank is just sitting in the barrier, what's the catching up that's happening?

**Comment by tpeterka** [comment]
Please ignore everything I said so far. MPI is sending and receiving everything in order, but the problem is on DIY's receiving side. In master, assume the slow rank has two messages waiting to be received, both from the same source and the same ir.info.round (=0). (Even though the user has multiple rounds, master has only one round because it is destroyed/created anew each time.)

The slow receiving rank is in check_incoming_queues() in the while(ostatus) loop. It receives the first message and places it at the start of the incoming queue of round 0. Iprobe is still true because there is one more message waiting. The second message is placed in the same location, overwriting the first message. The first message is lost, and the second message gets dequeued.

I have printfs that show two receives in the same while loop of check_incoming_queues() followed by only one dequeue of the second message.

Would that explain it?

**Comment by mrzv** [comment]
Yes. That makes perfect sense and explains everything. Thanks for figuring it out. It's also clear why `barrier` solves the problem. I currently don't see another solution. Shall we just add `barrier` to `Master::~Master`, as Sujin suggested?

**Comment by tpeterka** [comment]
Let's think on it. Overwriting messages in queues ought to be something we can control, but I don't know how badly that would break the exchange protocol. Certainly adding the barrier is an easy fix. But doing so would impose global synchronization across all ranks to what is fundamentally a local problem between only two ranks.

**Comment by mrzv** [comment]
True, we could identify that we've already received a message in a given round (at least in the regular exchange), but it's unclear to me how to "forward" the received message to the next Master.

But yeah, point taken, let's think on it.
